### ISSUE TITLE
Can not prepare and run any template

### ISSUE THREAD

**Issue by ddimitrioglo** [d6y/aws-gateway-mappping-playground#1]
```
[velocity]: scalac src/main/scala/runner.scala 
src/main/scala/runner.scala:1: error: object apache is not a member of package org
import org.apache.velocity.{Template, VelocityContext}
           ^
src/main/scala/runner.scala:2: error: object apache is not a member of package org
import org.apache.velocity.app.VelocityEngine
           ^
src/main/scala/runner.scala:8: error: not found: type Context
    context:  Context,
              ^
src/main/scala/runner.scala:9: error: not found: type Input
    input:    Input
              ^
src/main/scala/runner.scala:11: error: not found: type VelocityEngine
    val engine = new VelocityEngine()
                     ^
src/main/scala/runner.scala:12: error: not found: type VelocityContext
    val context = new VelocityContext()
                      ^
src/main/scala/runner.scala:30: error: not found: value Context
      Runner.run("src/test/resources/hello-world.vm", Context(), Input())
                                                      ^
src/main/scala/runner.scala:30: error: not found: value Input
      Runner.run("src/test/resources/hello-world.vm", Context(), Input())
                                                                 ^
8 errors found

```

**Comment by d6y** [comment]
Thanks for reporting this. I can't reproduce it at the moment (see [a gist of the output I get](https://gist.github.com/d6y/a7c88bdec85a73f18b3b176953afaa32)). Looks like somehow we're missing the dependency of apache velocity, but that does appear in the `build.sbt`.

I wonder if it's a java or sbt version problem (I notice I didn't include a `build.properties` in the repository)

**Comment by ddimitrioglo** [comment]
It's possible that I have not installed all the required dependencies, unfortunately I do not know nothing about scala or java... 
So probably the main issue here - lack of instructions how to prepare and initialize the repo in order to make it working.
Could you please describe the process from scratch?

**Comment by d6y** [comment]
Sure!

1. You need to install the build tool, sbt. The instructions can be found from: https://www.scala-sbt.org/

2. Clone this repository.

3. In the root folder, run: `sbt run` (UNIX) or `sbt.bat run` (Windows, I guess).

4. That will run the code in the file `src/main/scala/runner.scala`.  The `main` method in that class runs the template `src/test/resources/hello-world.vm` with a blank context and input. It will output "Hello  Velocity World!" in HTML.

5. You can edit the template or `runner.scala` and re-run sbt. Or... start sbt without any arguments, and at the sbt prompt enter: `~run` and that will run the code each time you change `runner.scala` (and possibly the `hello-world.vm` file.  (The `~` part means "watch for a change and run the command on change". You can leave that off and just type `run` each time instead).

Please let me know how you get on.

**Comment by ddimitrioglo** [comment]
thanks! will check it and come with updates!

**Comment by ddimitrioglo** [comment]
@d6y Everything is working! thanks a lot!
Here is the steps I've followed to run it on my **MacOS**:

- `brew install sbt@1`
- `git clone git@github.com:d6y/aws-gateway-mapping-playground.git`
- `sbt run`

That's it!

P.S. I think you can update your readme with these steps for scala newbies like me 😉

**Comment by d6y** [comment]
@ddimitrioglo great! thanks for letting me know 🎉
